-- =====================================================================
-- 02_sequences.sql
-- Applies Lesson 3 (Creating Sequences in PostgreSQL) directly.
--
-- Design decision: most tables use SERIAL for their surrogate key
-- because "SERIAL is simpler and sufficient for most single-table
-- auto-increment needs" (Lesson 3). However, two business-facing
-- identifiers need the extra control a manually created sequence gives
-- ("custom start values, increments, or sharing across tables" -
-- Lesson 3): BookingID (a customer-facing booking reference) and
-- InvoiceID (a legally sequential invoice number). These are exactly
-- the "OrderID, InvoiceNumber" use cases the lesson names.
-- =====================================================================

-- ---------------------------------------------------------------------
-- booking_ref_seq : mirrors the Lesson 3 practical exercise
-- (order_id_seq: START 5000, INCREMENT 1, NO CYCLE) applied to VRMS.
-- ---------------------------------------------------------------------
CREATE SEQUENCE booking_ref_seq
    START WITH 5000
    INCREMENT BY 1
    MINVALUE 5000
    MAXVALUE 999999
    NO CYCLE;

-- ---------------------------------------------------------------------
-- agreement_id_seq : internal rental-agreement numbering.
-- ---------------------------------------------------------------------
CREATE SEQUENCE agreement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO CYCLE;

-- ---------------------------------------------------------------------
-- invoice_number_seq : must start at a specific business-defined range
-- (finance requires invoices to start at 100000) and must never cycle
-- back to a used number - a duplicate invoice number would be a serious
-- audit problem. This is the clearest real justification in the whole
-- system for a manually created sequence instead of SERIAL.
-- ---------------------------------------------------------------------
CREATE SEQUENCE invoice_number_seq
    START WITH 100000
    INCREMENT BY 1
    MINVALUE 100000
    MAXVALUE 999999
    NO CYCLE;

-- Demonstrating NEXTVAL / CURRVAL / SETVAL exactly as taught:

-- NEXTVAL() advances the sequence and returns the next value.
SELECT NEXTVAL('booking_ref_seq') AS first_booking_reference;   -- 5000
SELECT NEXTVAL('booking_ref_seq') AS second_booking_reference;  -- 5001

-- CURRVAL() returns the value most recently generated by NEXTVAL() in
-- this session (raises an error if NEXTVAL() was never called first).
SELECT CURRVAL('booking_ref_seq') AS last_reference_issued;     -- 5001

-- SETVAL() manually sets the sequence. Here it is used to roll the demo
-- counter back so the two NEXTVAL() calls above (used only to prove the
-- concept) are not "wasted" before 05_sample_data.sql starts inserting
-- real rows. The third argument (is_called = false) tells PostgreSQL
-- that 5000 has NOT yet been consumed, so the next NEXTVAL() returns
-- exactly 5000 - this form must be used here because MINVALUE is 5000
-- and a plain SETVAL(seq, 4999) would fall outside the allowed range.
SELECT SETVAL('booking_ref_seq', 5000, false);   -- next NEXTVAL() call returns 5000 again

-- ALTER SEQUENCE is available for later maintenance, e.g. if the
-- business decides invoice numbers for the new financial year must
-- restart at 200000:
--   ALTER SEQUENCE invoice_number_seq RESTART WITH 200000;
-- (Not run here - included in the report as a documented example.)
